version: '3'
services:
  hacker-news:
    container_name: hacker-news
    image: node:13.12
    working_dir: /app
    environment:
      - NODE_ENV=production
      - IS_HN_SERVICE_ENABLED=false
    ports:
      - 8080:8080
      - 3000-3010:3000-3010
    command: yarn start
