version: 2.1
orbs:
  node: circleci/node@2.0.1

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build


  syncBranch:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Sync Downstream
          command: yarn rhinodeploy merge -c build:production


workflows:
  version: 2

  general:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - develop

  deployment:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - test:
          filters:
            branches:
              only:
                - master
                - develop
      - heroku/deploy-via-git:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
                - develop
      #- syncBranch:
      #   requires:
      #      - deploy
      #    filters:
      #      branches:
      #        only:
      #          - master
      #          - staging
      #          - develop
